# Generated by Django 4.1.6 on 2023-11-02 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="fruitBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller", models.CharField(max_length=255)),
                (
                    "fruit_requested",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("start_date", models.DateField()),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=15)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="fruitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fruitName", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="food_images/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="food.category"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FoodItem",
        ),
        migrations.AddField(
            model_name="fruitbooking",
            name="seller_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="food.fruititem"
            ),
        ),
    ]
