# Generated by Django 4.1.6 on 2023-11-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_fruitbooking_fruititem_delete_fooditem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fruititem",
            name="image",
            field=models.ImageField(blank=True, upload_to="food_images/"),
        ),
    ]
