# Generated by Django 4.1.6 on 2023-11-02 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fruitDisease", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImagePrediction",
        ),
    ]
